name: ToolReplenish
main: com.onyxchills.toolreplenish.ToolReplenishMain
version: 1.0.3

permissions:
    toolreplenish.fix:
        description: Gives ToolReplenish Ability     
        default: op                  